# Setup
title:            NuteBurn
tagline:          "A Grow Journal"
description:      "Just some asshole with a blog trying to grow some dank-ass weed."
url:              https://nuteburn.com
baseurl:          '/'
permalink:        /:title
paginate:         5
shareimage:       https://repository-images.githubusercontent.com/340120407/f9ffddfc-fa04-430c-bf5e-d97dc2002982
# Kramdown is used to generate the TOC on pages
markdown:         kramdown

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Author
author:
  name: "Nute Burn"
  email: nute@nuteburn.com

# SASS
sass:
  sass_dir: _sass
  style: :compressed
  implementation: sass-embedded

# Social Media Profiles
socialmedia:
  - title: Reddit
    link: https://www.reddit.com/user/Nute-burn
    user: Nute-Burn
    fa-icon: 'fab fa-reddit'

  - title: GitHub
    link: https://github.com/NuteBurn/nuteburn.github.io
    user: nuteburn
    fa-icon: 'fab fa-github'

  - title: Instagram
    link: https://www.instagram.com/topbudsonly/
    user: topbudsonly
    fa-icon: 'fab fa-instagram'