# Setup
title:            NuteBurn
tagline:          "A Grow Journal"
description:      "Just some asshole with a blog trying to grow some dank-ass weed."
url:              https://nuteburn.com
baseurl:          '/'
permalink:        /:title
shareimage:       https://repository-images.githubusercontent.com/340120407/f9ffddfc-fa04-430c-bf5e-d97dc2002982

# Kramdown is used to generate the TOC on pages
markdown:         kramdown

# Pagination
paginate:         5
paginate_path: "/blog/page:num/"

# Gems
plugins:
  - jekyll-paginate

# Author
author:
  name: "Nute Burn"
  email: nute@nuteburn.com

# SASS
sass:
  sass_dir: _sass
  style: compressed
  implementation: sass-embedded

# Social Media Profiles
socialmedia:

  - title: GitHub
    link: https://github.com/NuteBurn/nuteburn.github.io
    user: nuteburn
    fa-icon: 'fab fa-github'

#  - title: Mastodon
#    link: https://cannabiscats.cafe/@NuteBurn
#    user: NuteBurn
#    fa-icon: 'fab fa-mastodon'

  - title: Email
    link: "mailto:nute@nuteburn.com"
    user: NuteBurn
    fa-icon: 'fa-solid fa-envelope'
